config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "mini_scheduler/web"

# The following constants have been replaced with `RouteFormat` and are deprecated.
USERNAME_ROUTE_FORMAT = /[%\w.\-]+?/ unless defined? USERNAME_ROUTE_FORMAT
BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do
  def patch(*) end # Disable PATCH requests

  scope path: nil, constraints: { format: /(json|html|\*\/\*)/ } do
    relative_url_root = (defined?(Rails.configuration.relative_url_root) && Rails.configuration.relative_url_root) ? Rails.configuration.relative_url_root + '/' : '/'

    match "/404", to: "exceptions#not_found", via: [:get, :post]
    get "/404-body" => "exceptions#not_found_body"

    get "/bootstrap" => "bootstrap#index"

    post "webhooks/aws" => "webhooks#aws"
    post "webhooks/mailgun"  => "webhooks#mailgun"
    post "webhooks/mailjet"  => "webhooks#mailjet"
    post "webhooks/mandrill" => "webhooks#mandrill"
    post "webhooks/postmark" => "webhooks#postmark"
    post "webhooks/sendgrid" => "webhooks#sendgrid"
    post "webhooks/sparkpost" => "webhooks#sparkpost"

    scope path: nil, constraints: { format: /.*/ } do
      if Rails.env.development?
        mount Sidekiq::Web => "/sidekiq"
        mount Logster::Web => "/logs"
      else
        # only allow sidekiq in master site
        mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new(require_master: true)
        mount Logster::Web => "/logs", constraints: AdminConstraint.new
      end
    end

    resources :about do
      collection do
        get "live_post_counts"
      end
    end

    get "finish-installation" => "finish_installation#index"
    get "finish-installation/register" => "finish_installation#register"
    post "finish-installation/register" => "finish_installation#register"
    get "finish-installation/confirm-email" => "finish_installation#confirm_email"
    put "finish-installation/resend-email" => "finish_installation#resend_email"
    get "session/sase-login/:token" => "session#sase_login_info"
    get "pub/check-slug" => "published_pages#check_slug"
    get "pub/by-topic/:topic_id" => "published_pages#details"
    put "pub/by-topic/:topic_id" => "published_pages#upsert"
    delete "pub/by-topic/:topic_id" => "published_pages#destroy"
    get "pub/:slug" => "published_pages#show"

    resources :directory_items

    get "site" => "site#site"
    namespace :site do
      get "settings"
      get "custom_html"
      get "banner"
      get "emoji"
    end

    get "site/basic-info" => 'site#basic_info'
    get "site/statistics" => 'site#statistics'

    get "srv/status" => "forums#status"

    get "wizard" => "wizard#index"
    get 'wizard/steps' => 'steps#index'
    get 'wizard/steps/:id' => "wizard#index"
    put 'wizard/steps/:id' => "steps#update"

    namespace :admin, constraints: StaffConstraint.new do
      get "" => "admin#index"

      get 'plugins' => 'plugins#index'

      resources :site_settings, constraints: AdminConstraint.new do
        collection do
          get "category/:id" => "site_settings#index"
        end

        put "user_count" => "site_settings#user_count"
      end

      get "reports" => "reports#index"
      get "reports/bulk" => "reports#bulk"
      get "reports/:type" => "reports#show"

      resources :groups, only: [:create] do
        member do
          put "owners" => "groups#add_owners"
          delete "owners" => "groups#remove_owner"
          put "primary" => "groups#set_primary"
        end
      end
      resources :groups, except: [:create], constraints: AdminConstraint.new do
        collection do
          put "automatic_membership_count" => "groups#automatic_membership_count"
        end
      end

      get "groups/:type" => "groups#show", constraints: AdminConstraint.new
      get "groups/:type/:id" => "groups#show", constraints: AdminConstraint.new

      resources :users, id: RouteFormat.username, except: [:show] do
        collection do
          get "list" => "users#index"
          get "list/:query" => "users#index"
          get "ip-info" => "users#ip_info"
          delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
          get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
          put "approve-bulk" => "users#approve_bulk"
        end
        delete "penalty_history", constraints: AdminConstraint.new
        put "suspend"
        put "delete_posts_batch"
        put "unsuspend"
        put "revoke_admin", constraints: AdminConstraint.new
        put "grant_admin", constraints: AdminConstraint.new
        put "revoke_moderation", constraints: AdminConstraint.new
        put "grant_moderation", constraints: AdminConstraint.new
        put "approve"
        post "log_out", constraints: AdminConstraint.new
        put "activate"
        put "deactivate"
        put "silence"
        put "unsilence"
        put "trust_level"
        put "trust_level_lock"
        put "primary_group"
        post "groups" => "users#add_group", constraints: AdminConstraint.new
        delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
        get "badges"
        get "leader_requirements" => "users#tl3_requirements"
        get "tl3_requirements"
        put "anonymize"
        post "merge"
        post "reset_bounce_score"
        put "disable_second_factor"
        delete "sso_record"
      end
      get "users/:id.json" => 'users#show', defaults: { format: 'json' }
      get 'users/:id/:username' => 'users#show', constraints: { username: RouteFormat.username }
      get 'users/:id/:username/badges' => 'users#show'
      get 'users/:id/:username/tl3_requirements' => 'users#show'

      post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new

      resources :impersonate, constraints: AdminConstraint.new

      resources :email, constraints: AdminConstraint.new do
        collection do
          post "test"
          get "sent"
          get "skipped"
          get "bounced"
          get "received"
          get "rejected"
          get "/incoming/:id/raw" => "email#raw_email"
          get "/incoming/:id" => "email#incoming"
          get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
          get "preview-digest" => "email#preview_digest"
          get "send-digest" => "email#send_digest"
          get "smtp_should_reject"
          post "handle_mail"
          get "advanced-test"
          post "advanced-test" => "email#advanced_test"
        end
      end

      scope "/logs" do
        resources :staff_action_logs,     only: [:index]
        get 'staff_action_logs/:id/diff' => 'staff_action_logs#diff'
        resources :screened_emails,       only: [:index, :destroy]
        resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
          collection do
            post "roll_up"
          end
        end
        resources :screened_urls,         only: [:index]
        resources :search_logs,           only: [:index]
        get 'search_logs/term/' => 'search_logs#term'
      end

      get "/logs" => "staff_action_logs#index"

      # alias
      get '/logs/watched_words', to: redirect(relative_url_root + 'admin/customize/watched_words')
      get '/logs/watched_words/*path', to: redirect(relative_url_root + 'admin/customize/watched_words/%{path}')

      get "customize" => "color_schemes#index", constraints: AdminConstraint.new
      get "customize/themes" => "themes#index", constraints: AdminConstraint.new
      get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
      get "customize/colors/:id" => "color_schemes#index", constraints: AdminConstraint.new
      get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
      get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
      put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new

      resources :themes, constraints: AdminConstraint.new

      post "themes/import" => "themes#import"
      post "themes/upload_asset" => "themes#upload_asset"
      post "themes/generate_key_pair" => "themes#generate_key_pair"
      get "themes/:id/preview" => "themes#preview"
      put "themes/:id/setting" => "themes#update_single_setting"

      scope "/customize", constraints: AdminConstraint.new do
        resources :user_fields, constraints: AdminConstraint.new
        resources :emojis, constraints: AdminConstraint.new

        get 'themes/:id/:target/:field_name/edit' => 'themes#index'
        get 'themes/:id' => 'themes#index'
        get "themes/:id/export" => "themes#export"

        # They have periods in their URLs often:
        get 'site_texts'             => 'site_texts#index'
        get 'site_texts/:id.json'    => 'site_texts#show',   constraints: { id: /[\w.\-\+\%\&]+/i }
        get 'site_texts/:id'         => 'site_texts#show',   constraints: { id: /[\w.\-\+\%\&]+/i }
        put 'site_texts/:id.json'    => 'site_texts#update', constraints: { id: /[\w.\-\+\%\&]+/i }
        put 'site_texts/:id'         => 'site_texts#update', constraints: { id: /[\w.\-\+\%\&]+/i }
        delete 'site_texts/:id.json' => 'site_texts#revert', constraints: { id: /[\w.\-\+\%\&]+/i }
        delete 'site_texts/:id'      => 'site_texts#revert', constraints: { id: /[\w.\-\+\%\&]+/i }

        get 'reseed' => 'site_texts#get_reseed_options'
        post 'reseed' => 'site_texts#reseed'

        get 'email_templates'          => 'email_templates#index'
        get 'email_templates/(:id)'    => 'email_templates#show',   constraints: { id: /[0-9a-z_.]+/ }
        put 'email_templates/(:id)'    => 'email_templates#update', constraints: { id: /[0-9a-z_.]+/ }
        delete 'email_templates/(:id)' => 'email_templates#revert', constraints: { id: /[0-9a-z_.]+/ }

        get 'robots' => 'robots_txt#show'

app/models/concerns/reports/topics.rb
# frozen_string_literal: true

module Reports::Topics
  extend ActiveSupport::Concern

  class_methods do
    def report_topics(report)
      category_id, include_subcategories = report.add_category_filter

      basic_report_about report, Topic, :listable_count_per_day, report.start_date, report.end_date, category_id, include_subcategories

      countable = Topic.listable_topics
      countable = countable.where(category_id: include_subcategories ? Category.subcategory_ids(category_id) : category_id) if category_id

      add_counts report, countable, 'topics.created_at'
    end
  end
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

module TopicsHelper
  include ApplicationHelper

  def render_topic_title(topic)
    link_to(Emoji.gsub_emoji_to_unicode(topic.title), topic.relative_url)
  end

  def categories_breadcrumb(topic)
    breadcrumb = []
    category = topic.category

    if category && !category.uncategorized?
      breadcrumb.push(url: category.url, name: category.name, color: category.color)
      while category = category.parent_category
        breadcrumb.prepend(url: category.url, name: category.name, color: category.color)
      end
    end

    Plugin::Filter.apply(:topic_categories_breadcrumb, topic, breadcrumb)
  end

end

app/views/topics/plain.html.erb
<!DOCTYPE html>
<html lang="<%= html_lang %>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><%= @topic_view.topic.title %></title>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary(strip_images: true), image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count, published_time: @topic_view.published_time) %>
  <% if @topic_view.prev_page %>
    <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
  <% end %>
  <% if @topic_view.next_page %>
    <link rel="next" href="<%= @topic_view.next_page_path -%>">
  <% end %>
</head>
<body>
<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username %></b> <%= "(#{post.user.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names?) %> at <%= post.created_at.to_formatted_s(:long_ordinal) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>
<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>
</body>

app/views/topics/show.html.erb
<% if @topic_view %>
  <div id="topic-title">
    <h1>
      <%= render_topic_title(@topic_view.topic) %>
    </h1>

    <% if @breadcrumbs.present? %>
      <div class="topic-category" itemscope itemtype="http://schema.org/BreadcrumbList">
        <% @breadcrumbs.each_with_index do |c, i| %>
          <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a href="<%= Discourse.base_url %><%= c[:url] %>" class="badge-wrapper bullet" itemprop="item">
              <span class='badge-category-bg' style='background-color: #<%= c[:color] %>'></span>
              <span class='badge-category clear-badge'>
                <span class='category-name' itemprop='name'><%= c[:name] %></span>
              </span>
            </a>
            <meta itemprop="position" content="<%= i + 1 %>" />
          </span>
        <% end %>
      </div>
    <% end %>

    <% if @tags.present? %>
      <div class="topic-category">
        <div class='discourse-tags list-tags'>
          <% @tags.each_with_index do |tag, i| %>
            <a href='<%= "#{Discourse.base_url}/tag/#{tag.name}" %>' class='discourse-tag' rel="tag"><%= tag.name -%></a><% if i < @tags.size - 1 %>, <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= server_plugin_outlet "topic_header" %>

  <%- if include_crawler_content? %>

  <% @topic_view.posts.each_with_index do |post, idx| %>
    <% if (u = post.user) %>
      <div itemscope itemtype='http://schema.org/DiscussionForumPosting' class='topic-body crawler-post'>
        <div class='crawler-post-meta'>
          <div itemprop='publisher' itemscope itemtype="http://schema.org/Organization">
            <meta itemprop='name' content='<%= SiteSetting.company_name.presence || SiteSetting.title %>'>
            <% if application_logo_url.present? %>
              <div itemprop='logo' itemscope itemtype="http://schema.org/ImageObject">
                <meta itemprop='url' content='<%= application_logo_url %>'>
              </div>
            <% end %>
          </div>
          <span class="creator" itemprop="author" itemscope itemtype="http://schema.org/Person">
            <a itemprop="url" href='<%= Discourse.base_url %>/u/<%= u.username %>'><span itemprop='name'><%= u.username %></span></a>
            <%= "(#{u.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names? && !u.name.blank?) %>
            <%
              post_custom_fields = @topic_view.post_custom_fields[post.id] || {}
              who_username = post_custom_fields["action_code_who"] || ""
              small_action_href = post_custom_fields["action_code_path"] || ""
              if post.action_code
            %>
              <%= t("js.action_codes.#{post.action_code}", when: "", who: who_username, href: small_action_href).html_safe %>
            <% end %>
          </span>

          <link itemprop="mainEntityOfPage" href="<%= post.topic.url %>">

          <% if post.image_url %>
            <link itemprop="image" href="<%= post.image_url %>">
          <% end %>

          <span class="crawler-post-infos">
              <time itemprop='datePublished' datetime='<%= post.created_at.to_formatted_s(:iso8601) %>' class='post-time'>
                <%= l post.created_at, format: :long %>
              </time>
            <% if post.version > 1 %>
              <meta itemprop='dateModified' content='<%= post.last_version_at.to_formatted_s(:iso8601) %>'>
            <% else %>
              <meta itemprop='dateModified' content='<%= post.created_at.to_formatted_s(:iso8601) %>'>
            <% end %>
          <span itemprop='position'>#<%= post.post_number %></span>
          </span>
        </div>
        <div class='post' itemprop='articleBody'>
          <%= post.hidden ? t('flagging.user_must_edit').html_safe : post.cooked.html_safe %>
        </div>

        <meta itemprop='headline' content='<%= @topic_view.title %>'>
        <% if idx == 0 %>
          <meta itemprop='keywords' content='<%= @tags.map(&:name).join(', ') %>'>
        <% end %>

        <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
           <meta itemprop="interactionType" content="http://schema.org/LikeAction"/>
           <meta itemprop="userInteractionCount" content="<%= post.like_count %>" />
           <span class='post-likes'><%= post.like_count > 0 ? t('post.has_likes', count: post.like_count) : '' %></span>
         </div>

         <div itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter">
            <meta itemprop="interactionType" content="http://schema.org/CommentAction"/>
            <meta itemprop="userInteractionCount" content="<%= post.reply_count %>" />
          </div>

          <% if @topic_view.link_counts[post.id] && @topic_view.link_counts[post.id].filter { |l| l[:reflection] }.length > 0 %>
            <div class='crawler-linkback-list' itemscope itemtype='http://schema.org/ItemList'>
              <% @topic_view.link_counts[post.id].each_with_index do |link, i| %>
                <% if link[:reflection] && link[:title].present? %>
                  <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
                    <a href="<%=link[:url]%>" itemscope itemtype='http://schema.org/DiscussionForumPosting' itemprop='item'>
                      <meta itemprop='url' content='<%=link[:url]%>'>
                      <span itemprop='name'><%=link[:title]%></span>
                    </a>
                    <meta itemprop='position' content='<%= i+1 %>'>
                  </div>
                <% end %>
              <% end %>
            </div>
         <% end %>
      </div>
    <% end %>
  <% end %>

  <% if @topic_view.prev_page || @topic_view.next_page %>
    <div role='navigation' itemscope itemtype='http://schema.org/SiteNavigationElement' class="topic-body crawler-post">
      <% if @topic_view.prev_page %>
        <span itemprop='name'><%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev', itemprop: 'url' %></span>
      <% end %>
      <% if @topic_view.next_page %>
        <span itemprop='name'><b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next', itemprop: 'url' %></b></span>
      <% end %>
    </div>
  <% end %>

  <% end %>

  <% content_for :head do %>
    <%= auto_discovery_link_tag(@topic_view, {action: :feed, slug: @topic_view.topic.slug, topic_id: @topic_view.topic.id}, title: t('rss_posts_in_topic', topic: @topic_view.title), type: 'application/rss+xml') %>
    <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary(strip_images: true), image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count, ignore_canonical: true, published_time: @topic_view.published_time) %>

    <% if @topic_view.prev_page || @topic_view.next_page %>
      <% if @topic_view.prev_page %>
        <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
      <% end %>
      <% if @topic_view.next_page %>
        <link rel="next" href="<%= @topic_view.next_page_path -%>">
      <% end %>
    <% end %>
  <% end %>

  <% content_for(:title) { @title || "#{gsub_emoji_to_unicode(@topic_view.page_title)} - #{SiteSetting.title}" } %>

  <% if @topic_view.print %>
    <% content_for :after_body do %>
        <%= preload_script('print-page') %>
    <% end %>
  <% end %>
<% end %>

app/views/topics/show.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <% topic_url = @topic_view.absolute_url %>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @topic_view.title %></title>
    <link><%= topic_url %></link>
    <description><%= @topic_view.posts.first.raw %></description>
    <% if lang %><language><%= lang.sub('_', '-')%></language><% end %>
    <lastBuildDate><%= @topic_view.topic.bumped_at.rfc2822 %></lastBuildDate>
    <category><%= @topic_view.topic.category.name %></category>
    <atom:link href="<%= topic_url %>.rss" rel="self" type="application/rss+xml" />
    <% @topic_view.recent_posts.each do |post| %>
      <% next unless post.user %>
      <item>
        <title><%= @topic_view.title %></title>
        <dc:creator><![CDATA[<%= rss_creator(post.user) -%>]]></dc:creator>
        <description><![CDATA[
          <% post_url = Discourse.base_url + post.url %>
          <% if post.hidden %>
            <%= t('flagging.user_must_edit').html_safe %>
          <% else %>
            <%= PrettyText.format_for_email(post.cooked, post).html_safe %>
          <% end %>
          <p><%= link_to t('read_full_topic'), post_url %></p>
        ]]></description>
        <link><%= post_url %></link>
        <pubDate><%= post.created_at.rfc2822 %></pubDate>
        <guid isPermaLink="false"><%= Discourse.current_hostname %>-post-<%= post.topic_id %>-<%= post.post_number %></guid>
        <source url="<%= topic_url %>.rss"><%= @topic_view.title %></source>
      </item>
    <% end %>
  </channel>
</rss>