config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "mini_scheduler/web"

# The following constants have been replaced with `RouteFormat` and are deprecated.
USERNAME_ROUTE_FORMAT = /[%\w.\-]+?/ unless defined? USERNAME_ROUTE_FORMAT
BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do
  def patch(*) end # Disable PATCH requests

  scope path: nil, constraints: { format: /(json|html|\*\/\*)/ } do
    relative_url_root = (defined?(Rails.configuration.relative_url_root) && Rails.configuration.relative_url_root) ? Rails.configuration.relative_url_root + '/' : '/'

    match "/404", to: "exceptions#not_found", via: [:get, :post]
    get "/404-body" => "exceptions#not_found_body"

    get "/bootstrap" => "bootstrap#index"

    post "webhooks/aws" => "webhooks#aws"
    post "webhooks/mailgun"  => "webhooks#mailgun"
    post "webhooks/mailjet"  => "webhooks#mailjet"
    post "webhooks/mandrill" => "webhooks#mandrill"
    post "webhooks/postmark" => "webhooks#postmark"
    post "webhooks/sendgrid" => "webhooks#sendgrid"
    post "webhooks/sparkpost" => "webhooks#sparkpost"

    scope path: nil, constraints: { format: /.*/ } do
      if Rails.env.development?
        mount Sidekiq::Web => "/sidekiq"
        mount Logster::Web => "/logs"
      else
        # only allow sidekiq in master site
        mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new(require_master: true)
        mount Logster::Web => "/logs", constraints: AdminConstraint.new
      end
    end

    resources :about do
      collection do
        get "live_post_counts"
      end
    end

    get "finish-installation" => "finish_installation#index"
    get "finish-installation/register" => "finish_installation#register"
    post "finish-installation/register" => "finish_installation#register"
    get "finish-installation/confirm-email" => "finish_installation#confirm_email"
    put "finish-installation/resend-email" => "finish_installation#resend_email"
    get "session/sase-login/:token" => "session#sase_login_info"
    get "pub/check-slug" => "published_pages#check_slug"
    get "pub/by-topic/:topic_id" => "published_pages#details"
    put "pub/by-topic/:topic_id" => "published_pages#upsert"
    delete "pub/by-topic/:topic_id" => "published_pages#destroy"
    get "pub/:slug" => "published_pages#show"

    resources :directory_items

    get "site" => "site#site"
    namespace :site do
      get "settings"
      get "custom_html"
      get "banner"
      get "emoji"
    end

    get "site/basic-info" => 'site#basic_info'
    get "site/statistics" => 'site#statistics'

    get "srv/status" => "forums#status"

    get "wizard" => "wizard#index"
    get 'wizard/steps' => 'steps#index'
    get 'wizard/steps/:id' => "wizard#index"
    put 'wizard/steps/:id' => "steps#update"

    namespace :admin, constraints: StaffConstraint.new do
      get "" => "admin#index"

      get 'plugins' => 'plugins#index'

      resources :site_settings, constraints: AdminConstraint.new do
        collection do
          get "category/:id" => "site_settings#index"
        end

        put "user_count" => "site_settings#user_count"
      end

      get "reports" => "reports#index"
      get "reports/bulk" => "reports#bulk"
      get "reports/:type" => "reports#show"

      resources :groups, only: [:create] do
        member do
          put "owners" => "groups#add_owners"
          delete "owners" => "groups#remove_owner"
          put "primary" => "groups#set_primary"
        end
      end
      resources :groups, except: [:create], constraints: AdminConstraint.new do
        collection do
          put "automatic_membership_count" => "groups#automatic_membership_count"
        end
      end

      get "groups/:type" => "groups#show", constraints: AdminConstraint.new
      get "groups/:type/:id" => "groups#show", constraints: AdminConstraint.new

      resources :users, id: RouteFormat.username, except: [:show] do
        collection do
          get "list" => "users#index"
          get "list/:query" => "users#index"
          get "ip-info" => "users#ip_info"
          delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
          get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
          put "approve-bulk" => "users#approve_bulk"
        end
        delete "penalty_history", constraints: AdminConstraint.new
        put "suspend"
        put "delete_posts_batch"
        put "unsuspend"
        put "revoke_admin", constraints: AdminConstraint.new
        put "grant_admin", constraints: AdminConstraint.new
        put "revoke_moderation", constraints: AdminConstraint.new
        put "grant_moderation", constraints: AdminConstraint.new
        put "approve"
        post "log_out", constraints: AdminConstraint.new
        put "activate"
        put "deactivate"
        put "silence"
        put "unsilence"
        put "trust_level"
        put "trust_level_lock"
        put "primary_group"
        post "groups" => "users#add_group", constraints: AdminConstraint.new
        delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
        get "badges"
        get "leader_requirements" => "users#tl3_requirements"
        get "tl3_requirements"
        put "anonymize"
        post "merge"
        post "reset_bounce_score"
        put "disable_second_factor"
        delete "sso_record"
      end
      get "users/:id.json" => 'users#show', defaults: { format: 'json' }
      get 'users/:id/:username' => 'users#show', constraints: { username: RouteFormat.username }
      get 'users/:id/:username/badges' => 'users#show'
      get 'users/:id/:username/tl3_requirements' => 'users#show'

      post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new

      resources :impersonate, constraints: AdminConstraint.new

      resources :email, constraints: AdminConstraint.new do
        collection do
          post "test"
          get "sent"
          get "skipped"
          get "bounced"
          get "received"
          get "rejected"
          get "/incoming/:id/raw" => "email#raw_email"
          get "/incoming/:id" => "email#incoming"
          get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
          get "preview-digest" => "email#preview_digest"
          get "send-digest" => "email#send_digest"
          get "smtp_should_reject"
          post "handle_mail"
          get "advanced-test"
          post "advanced-test" => "email#advanced_test"
        end
      end

      scope "/logs" do
        resources :staff_action_logs,     only: [:index]
        get 'staff_action_logs/:id/diff' => 'staff_action_logs#diff'
        resources :screened_emails,       only: [:index, :destroy]
        resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
          collection do
            post "roll_up"
          end
        end
        resources :screened_urls,         only: [:index]
        resources :search_logs,           only: [:index]
        get 'search_logs/term/' => 'search_logs#term'
      end

      get "/logs" => "staff_action_logs#index"

      # alias
      get '/logs/watched_words', to: redirect(relative_url_root + 'admin/customize/watched_words')
      get '/logs/watched_words/*path', to: redirect(relative_url_root + 'admin/customize/watched_words/%{path}')

      get "customize" => "color_schemes#index", constraints: AdminConstraint.new
      get "customize/themes" => "themes#index", constraints: AdminConstraint.new
      get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
      get "customize/colors/:id" => "color_schemes#index", constraints: AdminConstraint.new
      get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
      get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
      put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new

      resources :themes, constraints: AdminConstraint.new

      post "themes/import" => "themes#import"
      post "themes/upload_asset" => "themes#upload_asset"
      post "themes/generate_key_pair" => "themes#generate_key_pair"
      get "themes/:id/preview" => "themes#preview"
      put "themes/:id/setting" => "themes#update_single_setting"

      scope "/customize", constraints: AdminConstraint.new do
        resources :user_fields, constraints: AdminConstraint.new
        resources :emojis, constraints: AdminConstraint.new

        get 'themes/:id/:target/:field_name/edit' => 'themes#index'
        get 'themes/:id' => 'themes#index'
        get "themes/:id/export" => "themes#export"

        # They have periods in their URLs often:
        get 'site_texts'             => 'site_texts#index'
        get 'site_texts/:id.json'    => 'site_texts#show',   constraints: { id: /[\w.\-\+\%\&]+/i }
        get 'site_texts/:id'         => 'site_texts#show',   constraints: { id: /[\w.\-\+\%\&]+/i }
        put 'site_texts/:id.json'    => 'site_texts#update', constraints: { id: /[\w.\-\+\%\&]+/i }
        put 'site_texts/:id'         => 'site_texts#update', constraints: { id: /[\w.\-\+\%\&]+/i }
        delete 'site_texts/:id.json' => 'site_texts#revert', constraints: { id: /[\w.\-\+\%\&]+/i }
        delete 'site_texts/:id'      => 'site_texts#revert', constraints: { id: /[\w.\-\+\%\&]+/i }

        get 'reseed' => 'site_texts#get_reseed_options'
        post 'reseed' => 'site_texts#reseed'

        get 'email_templates'          => 'email_templates#index'
        get 'email_templates/(:id)'    => 'email_templates#show',   constraints: { id: /[0-9a-z_.]+/ }
        put 'email_templates/(:id)'    => 'email_templates#update', constraints: { id: /[0-9a-z_.]+/ }
        delete 'email_templates/(:id)' => 'email_templates#revert', constraints: { id: /[0-9a-z_.]+/ }

        get 'robots' => 'robots_txt#show'

app/models/about.rb
# frozen_string_literal: true

class About
  class CategoryMods
    include ActiveModel::Serialization
    attr_reader :category_id, :moderators

    def initialize(category_id, moderators)
      @category_id = category_id
      @moderators = moderators
    end
  end

  include ActiveModel::Serialization
  include StatsCacheable

  attr_accessor :moderators,
                :admins

  def self.stats_cache_key
    'about-stats'
  end

  def self.fetch_stats
    About.new.stats
  end

  def initialize(user = nil)
    @user = user
  end

  def version
    Discourse::VERSION::STRING
  end

  def https
    SiteSetting.force_https
  end

  def title
    SiteSetting.title
  end

  def locale
    SiteSetting.default_locale
  end

  def description
    SiteSetting.site_description
  end

  def moderators
    @moderators ||= User.where(moderator: true, admin: false)
      .human_users
      .order("last_seen_at DESC")
  end

  def admins
    @admins ||= User.where(admin: true)
      .human_users
      .order("last_seen_at DESC")
  end

  def stats
    @stats ||= {
      topic_count: Topic.listable_topics.count,
      topics_last_day: Topic.listable_topics.where('created_at > ?', 1.days.ago).count,
      topics_7_days: Topic.listable_topics.where('created_at > ?', 7.days.ago).count,
      topics_30_days: Topic.listable_topics.where('created_at > ?', 30.days.ago).count,
      post_count: Post.count,
      posts_last_day: Post.where('created_at > ?', 1.days.ago).count,
      posts_7_days: Post.where('created_at > ?', 7.days.ago).count,
      posts_30_days: Post.where('created_at > ?', 30.days.ago).count,
      user_count: User.real.count,
      users_last_day: User.real.where('created_at > ?', 1.days.ago).count,
      users_7_days: User.real.where('created_at > ?', 7.days.ago).count,
      users_30_days: User.real.where('created_at > ?', 30.days.ago).count,
      active_users_last_day: User.where('last_seen_at > ?', 1.days.ago).count,
      active_users_7_days: User.where('last_seen_at > ?', 7.days.ago).count,
      active_users_30_days: User.where('last_seen_at > ?', 30.days.ago).count,
      like_count: UserAction.where(action_type: UserAction::LIKE).count,
      likes_last_day: UserAction.where(action_type: UserAction::LIKE).where("created_at > ?", 1.days.ago).count,
      likes_7_days: UserAction.where(action_type: UserAction::LIKE).where("created_at > ?", 7.days.ago).count,
      likes_30_days: UserAction.where(action_type: UserAction::LIKE).where("created_at > ?", 30.days.ago).count
    }
  end

  def category_moderators
    allowed_cats = Guardian.new(@user).allowed_category_ids
    return [] if allowed_cats.blank?

    cats_with_mods = Category.where.not(reviewable_by_group_id: nil).pluck(:id)

    category_ids = cats_with_mods & allowed_cats
    return [] if category_ids.blank?

    per_cat_limit = category_mods_limit / category_ids.size
    per_cat_limit = 1 if per_cat_limit < 1

    results = DB.query(<<~SQL, category_ids: category_ids)
        SELECT c.id category_id
             , (ARRAY_AGG(u.id ORDER BY u.last_seen_at DESC))[:#{per_cat_limit}] user_ids
          FROM categories c
          JOIN group_users gu ON gu.group_id = c.reviewable_by_group_id
          JOIN users u ON u.id = gu.user_id
         WHERE c.id IN (:category_ids)
      GROUP BY c.id
      ORDER BY c.position
    SQL

    mods = User.where(id: results.map(&:user_ids).flatten.uniq).index_by(&:id)

    results.map do |row|
      CategoryMods.new(row.category_id, mods.values_at(*row.user_ids))
    end
  end

  def category_mods_limit
    @category_mods_limit || 100
  end

  def category_mods_limit=(number)
    @category_mods_limit = number
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController

  requires_login only: [:live_post_counts]

  skip_before_action :check_xhr, only: [:index]

  def index
    return redirect_to path('/login') if SiteSetting.login_required? && current_user.nil?

    @about = About.new(current_user)
    @title = "#{I18n.t("js.about.simple_title")} - #{SiteSetting.title}"
    respond_to do |format|
      format.html do
        render :index
      end
      format.json do
        render_json_dump(AboutSerializer.new(@about, scope: guardian))
      end
    end
  end

  def live_post_counts
    RateLimiter.new(current_user, "live_post_counts", 1, 10.minutes).performed! unless current_user.staff?
    category_topic_ids = Category.pluck(:topic_id).compact!
    public_topics = Topic.listable_topics.visible.secured(Guardian.new(nil)).where.not(id: category_topic_ids)
    stats = { public_topic_count: public_topics.count }
    stats[:public_post_count] = public_topics.sum(:posts_count) - stats[:public_topic_count]
    render json: stats
  end
end

app/views/about/index.html.erb
<% if crawler_layout? %>

<section itemscope itemtype="https://schema.org/AboutPage">
  <h1 itemprop="name">
    <%=t "js.about.title", **{title: @about.title} %>
  </h1>

  <div itemprop="text">
    <%= @about.description %>
  </div>

  <h2><%=t "js.about.our_admins" %></h2>

  <div class='admins-list' itemscope itemtype='http://schema.org/ItemList'>
    <% @about.admins.each do |user| %>
      <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
        <meta itemprop='url' content='<%= user_path(user.username_lower) %>'>
        <a href='<%= user_path(user.username_lower) %>' itemprop='item'>
          <span itemprop='image'>
            <img width="45" height="45" class="avatar" src="<%= user.small_avatar_url %>">
          </span>
          <span itemprop='name'>
            <%= user.username %>
            <% if user.name.present? && SiteSetting.enable_names %>
              - <%= user.name %>
            <% end %>
          </span>
        </a>
      </div>
    <% end %>
  </div>

  <% if @about.moderators.count > 0 %>
    <h2><%=t "js.about.our_moderators" %></h2>
    <div class='moderators-list' itemscope itemtype='http://schema.org/ItemList'>
      <% @about.moderators.each do |user| %>
        <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
          <meta itemprop='url' content='<%= user_path(user.username_lower) %>'>
          <a href='<%= user_path(user.username_lower) %>' itemprop='item'>
            <span itemprop='image'>
              <img width="45" height="45" class="avatar" src="<%= user.small_avatar_url %>">
            </span>
            <span itemprop='name'>
              <%= user.username %>
              <% if user.name.present? && SiteSetting.enable_names %>
                - <%= user.name %>
              <% end %>
            </span>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>

  <%- stats = About.fetch_cached_stats %>

  <section class='about stats'>
    <h2><%=t 'js.about.stats' %></h2>

    <table class='table'>
      <tr>
        <th>&nbsp;</th>
        <th><%=t 'js.about.stat.all_time' %></th>
        <th><%=t 'js.about.stat.last_day' %></th>
        <th><%=t 'js.about.stat.last_7_days' %></th>
        <th><%=t 'js.about.stat.last_30_days' %></th>
      </tr>
      <tr>
        <td class='title'><%=t 'js.about.topic_count' %></td>
        <td><%= stats["topic_count"] %></td>
        <td><%= stats["topics_last_day"] %></td>
        <td><%= stats["topics_7_days"] %></td>
        <td><%= stats["topics_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.post_count' %></td>
        <td><%= stats["post_count"] %></td>
        <td><%= stats["posts_last_day"] %></td>
        <td><%= stats["posts_7_days"] %></td>
        <td><%= stats["posts_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.user_count' %></td>
        <td><%= stats["user_count"] %></td>
        <td><%= stats["users_last_day"] %></td>
        <td><%= stats["users_7_days"] %></td>
        <td><%= stats["users_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.active_user_count' %></td>
        <td>&mdash;</td>
        <td><%= stats["active_users_last_day"] %></td>
        <td><%= stats["active_users_7_days"] %></td>
        <td><%= stats["active_users_30_days"] %></td>
      </tr>
      <tr>
        <td><%=t 'js.about.like_count' %></td>
        <td><%= stats["like_count"] %></td>
        <td><%= stats["likes_last_day"] %></td>
        <td><%= stats["likes_7_days"] %></td>
        <td><%= stats["likes_30_days"] %></td>
      </tr>
    </table>
  </section>

</section>
<br/>
<br/>

<% end %>

<% if @title %>
  <% content_for :title do %><%= @title %><% end %>
  <% content_for :head do %>
    <%= raw crawlable_meta_data(title: @title, description: SiteSetting.site_description) %>
  <% end %>
<% else %>
  <% content_for :head do %>
    <%= raw crawlable_meta_data(title: SiteSetting.title, description: SiteSetting.site_description) %>
  <% end %>
<% end %>